# List all your repositories, e.g.:
#
#   repos_name_1:
#     type: restlike
#     url: http://acrs.company.com/1/repos_name_1
#     files: http://assets.company.com
#
#   repos_name_2:
#     type: mysqlschemaless
#     host:       127.0.0.1
#     dbname:     anycontent
#     user:       dbuser
#     password:   password
#
#    repos_name_3:
#       type: archive
#       folder: /var/www/repos/name_3
#       files: true
#
#  Additionally you can specify a distinct filemanager
#
#    repos_name_2:
#       ...
#       filemanager:
#         type: restlike
#         repository_url: http://acrs.company.com/1/repos_name_1
#         files_url: http://assets.company.com
#
#    repos_name_3:
#       ...
#       filemanager:
#         type: directory
#         path: var/www/assets
#         files_url: http://assets.company.com
#
#

repositories:


#
# If you want to access non standard repositories, add them via repositories.php
#


userinfo:
  username:   john@example.org
  firstname:  John
  lastname:   Doe

#
# cache settings
#
# seconds_caching_api_responses determines how long a api result gets cached. It will get invalid, if you
# perform a write operation.
# seconds_ignoring_eventually_concurrent_writes determines how often you request the repositoy info. If set to 0
# you might perform multiple requests during one operation, so better keep the default of 1 second. If your client
# is the only client operating with the API, you can raise the value, otherwise keep it low to avoid confusing results.
#

cache:
  driver: {type: apc}
  seconds_caching_menu: 600
  seconds_caching_api_responses: 3600
  seconds_ignoring_eventually_concurrent_writes: 1
  seconds_ignoring_eventually_concurrent_file_updates: 15


authentication:
  type: config
  users:
     - {username: john@example.org, firstname: John, lastname: Doe, password: john@example.org, encryption: none }

# Activate REST like service
#
#service:
#     path: "/acrs"

# Activate HTTP Caching - recommend if using the rest service
#
#http_cache: true